export const products = [
  { id: 1, name: "Jacket", price: 100, category: "Men", color: "Black", size: "M", img: "../assets/photos/Jacket.jpg" },
  { id: 2, name: "Dress", price: 150, category:"Woman", color: "White", size: "S", img: "../assets/photos/Dress.jpg" },
  { id: 3, name: "T-shirt", price: 80, category: "Men", color: "Black", size: "L", img: "../assets/photos/tishert.jpg" },
  { id: 4, name: "T-shirt", price: 90, category: "Men", color: "Black", size: "S", img: "../assets/photos/tishert-black.jpg" },
  { id: 5, name: "T-shirt", price: 70, category: "Men", color: "Blue", size: "M", img: "../assets/photos/tishert-blue.jpg" },
  { id: 6, name: "Jacket", price: 120, category: "Woman", color: "Black", size: "S", img: "../assets/photos/jaket-black.jpg" },
  { id: 7, name: "Jacket", price: 130, category: "Woman", color: "Red", size: "M", img: "../assets/photos/jaket-red.jpg" },
  { id: 8, name: "Jacket", price: 125, category: "Men", color: "White", size: "L", img: "../assets/photos/jacket-white.jpg" },
  { id: 9, name: "Jacket", price: 155, category: "Men", color: "Black", size: "M", img: "../assets/photos/jacket-black.jpg" },
  { id: 10, name: "T-shirt", price: 90, category: "Men", color: "Green", size: "S", img: "../assets/photos/tishert-green.jpg" },
  { id: 11, name: "Dress", price: 200, category: "Woman", color: "Green", size: "M", img: "../assets/photos/dress1.jpg" },
  { id: 12, name: "Dress", price: 320, category: "Woman", color: "Green", size: "S", img: "../assets/photos/dress2.jpg" },
  { id: 13, name: "Dress", price: 400, category: "Woman", color: "Red", size: "M", img: "../assets/photos/dress3.jpg" }, 
  { id: 14, name: "Dress", price:250, category: "Woman", color: "Blue", size: "M", img: "../assets/photos/dress-blue.jpg" },
  { id: 15, name: "Dress", price: 180, category: "Woman", color: "Green", size: "L", img: "../assets/photos/jacket-green.jpg" },
  { id: 16, name: "Dress Kids", price: 50, category: "Kids", color: "Black", size: "L", img: "../assets/photos/kids-black.jpg" }, 
  { id: 17, name: "Dress Kids", price: 55, category: "Kids", color: "Red", size: "S", img: "../assets/photos/kids-red.jpg" }, 
  { id: 18, name: "Dress Kids", price: 60, category: "Kids", color: "Blue", size: "S", img: "../assets/photos/kids-blue.jpg" }, 
  { id: 19, name: "T-shirt Sport", price: 77, category: "Sport", color: "Black", size: "L", img: "../assets/photos/sport-black.jpg" }, 
  { id: 20, name: "T-shirt Sport", price: 100, category: "Sport", color: "Black", size: "M", img: "../assets/photos/sport-black2.jpg" }, 
  { id: 21, name: "T-shirt Sport", price: 55, category: "Sport", color: "White", size: "M", img: "../assets/photos/sport-white.jpg" }, 
  { id: 22, name: "T-shirt Sport", price: 90, category: "Sport", color: "Red", size: "S", img: "../assets/photos/sport-red.jpg" }, 
];